apiVersion: apps/v1
kind: Deployment
metadata:
  name: filestore-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filestore-server
  template:
    metadata:
      labels:
        app: filestore-server
    spec:
      containers:
        - name: server
          image: yourusername/filestore-server:v1
          ports:
            - containerPort: 5000
